package exception

import "errors"

var ErrAlreadyExist = errors.New("data is already exist")
